pipeline {

    agent any

    parameters {

        choice(
            name: 'ENVIRONMENT',
            choices: ['dev', 'qa', 'prod'],
            description: 'Select deployment environment'
        )

        string(
            name: 'AWS_REGION',
            defaultValue: 'ap-south-1',
            description: 'AWS region'
        )

        string(
            name: 'AMI_ID',
            defaultValue: '',
            description: 'AMI ID'
        )

        choice(
            name: 'INSTANCE_TYPE',
            choices: ['t2.micro', 't3.micro', 't3.small'],
            description: 'EC2 instance type'
        )

        string(
            name: 'INSTANCE_NAME',
            defaultValue: 'dev-server',
            description: 'EC2 instance name'
        )
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir('infrastructure') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('infrastructure') {
                    sh 'terraform validate'
                }
            }
        }
    }
}