pipeline {

    agent any

    parameters {

        choice(
            name: 'ENVIRONMENT',
            choices: ['dev', 'qa', 'prod'],
            description: 'Select deployment environment'
        )

        string(
            name: 'AWS_REGION',
            defaultValue: 'ap-south-1',
            description: 'AWS region'
        )

        string(
            name: 'AMI_ID',
            defaultValue: '',
            description: 'AMI ID'
        )

        choice(
            name: 'INSTANCE_TYPE',
            choices: ['t2.micro', 't3.micro', 't3.small'],
            description: 'Select EC2 instance type'
        )

        string(
            name: 'INSTANCE_NAME',
            defaultValue: 'dev-server',
            description: 'EC2 instance name'
        )
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
stage('AWS Authentication Test') {
    steps {
        withCredentials([
            [$class: 'AmazonWebServicesCredentialsBinding',
             credentialsId: 'jenkins-aws']
        ]) {
            sh '''
                aws sts get-caller-identity
            '''
        }
    }
}
        stage('Terraform Init') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('terraform') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform') {
                    sh """
                        terraform plan \
                        -var="aws_region=${params.AWS_REGION}" \
                        -var="ami_id=${params.AMI_ID}" \
                        -var="instance_type=${params.INSTANCE_TYPE}" \
                        -var="instance_name=${params.INSTANCE_NAME}" \
                        -var="environment=${params.ENVIRONMENT}"
                    """
                }
            }
        }

        stage('Approval') {
            steps {
                input message: "Do you want to create ${params.INSTANCE_NAME}?", 
                      ok: "Proceed"
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    sh """
                        terraform apply -auto-approve \
                        -var="aws_region=${params.AWS_REGION}" \
                        -var="ami_id=${params.AMI_ID}" \
                        -var="instance_type=${params.INSTANCE_TYPE}" \
                        -var="instance_name=${params.INSTANCE_NAME}" \
                        -var="environment=${params.ENVIRONMENT}"
                    """
                }
            }
        }

        stage('Terraform Output') {
            steps {
                dir('terraform') {
                    sh 'terraform output'
                }
            }
        }
    }
}